cornershop-backend-test/backend_test/urls.py
from django.urls import path, include

from menus.views import CreateMenuView
from menus.views import ListMenuView
from menus.views import PublishMenuView
from menus.views import DetailMenuView
from menus.views import ListEmployeesSelectionView
from menus.views import Index

from employees.views import EmployeeSelectionsList

from .utils.healthz import healthz


urlpatterns = [
    path("healthz", healthz, name="healthz"),
    path('', Index.as_view(), name="index"),
    path('menus/add/', CreateMenuView.as_view(), name="create_menu"),
    path('menus/', ListMenuView.as_view(), name="list_menus"),
    path('menus/<uuid:id>/publish/', PublishMenuView.as_view(), name="publish_menu"),
    path('menus/<uuid:id>/', DetailMenuView.as_view(), name="detail_menu"),
    path('menus/<uuid:id>/employees/', ListEmployeesSelectionView.as_view(), name="selection"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('employee/orders/', EmployeeSelectionsList.as_view(), name='employee_selection')
]

cornershop-backend-test/menus/models/employee_selection.py
"""This module contains the specification of the model responsible
of managing the orders of the employees in corporate."""
from django.db import models

class EmployeeSelection(models.Model):
    """This model contains the reference of an option
    of a menu and the employee that is the propetary
    of that order. We require this menu in order to
    store also the customization of a selected option."""
    menu_option = models.ForeignKey(
        'MenuOption',
        on_delete=models.CASCADE
    )
    employee = models.ForeignKey(
        'employees.Employee',
        on_delete=models.CASCADE
    )
    customization = models.TextField(null=True)

cornershop-backend-test/menus/models/menu.py
"""This module contains the specification of the Menu model an its
associated methods."""
from django.db import models
from django.conf import settings

import uuid

from backend_test.celery import app

from .menu_option import MenuOption
from .managers.menu_manager import MenuManager

from menus.exceptions import NotValidMenuOption

class Menu(models.Model):
    """Its the object capable of manage the options that can
    be served on an specific day for the employees."""
    id = models.UUIDField(
        'The identifier field of the menu',
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.TextField(
        'The name of the menu that is going to be served.'
    )
    date = models.DateField(
        'The date which the menu is going to be served.'
    )
    expiration_date_time = models.DateTimeField(
        'The limited date and time to request an option of a menu'
    )
    is_published = models.BooleanField(
        default=False
    )
    objects = MenuManager()

    def publish(self):
        """This method is in charge of calling the
        task that will send a message to the users in a certain
        group with the options of the menu in an specific day"""
        app.send_task('menus.tasks.publish_menu', (self.id,))

    def get_options_for_slack(self):
        """Returns the list of elements that are
        part of a particular day in a format that
        can be interpreted by slack. The value of
        an option is always string because of the
        slack specification.

        :return: The list of menu options with elements
                 with the next format.
                 {
                    value: Uses the id of the option,
                    text: {
                        type: Always as plain_text,
                        text: A formatted text that contains the
                        concat of the option name and the option
                        description
                    }

                 }
        :rtype list
        """
        return [
            {
                'value': str(option.id),
                'text': {
                    'type': 'plain_text',
                    'text': '%s %s' % (
                        option.name,
                        option.description
                    )
                }
            }
            for option in self.menuoption_set.all().iterator()
        ]

    def get_option(self, option_id):
        """Returns an option of a menu based on the id.
        As slack manages id's in radio buttons as strings
        it is required to parse the option_id parameter
        into an integer.

        :param option_id: The id of selected option
        :type  option_id: str

        :return:    A reference to a valid option
                    of the current menu
        :rtype      MenuOption
        """
        option_id = int(option_id)
        option = self.menuoption_set.filter(
            id=option_id
        )
        if option.exists():
            return option.first()
        raise NotValidMenuOption

cornershop-backend-test/menus/models/menu_option.py
"""This module contains the specification of the options
available on a menu."""

from django.db import models

class MenuOption(models.Model):
    """The objects of this class or this model contains the
    information related to the options that can be selected
    by an employee from an specific menu."""
    name = models.TextField(
        'The name of an option'
    )
    description = models.TextField(
        'The description of a menu. It can contains ingredients'
        ' or other required specification in order to let know '
        ' the employees the things used to prepare an option.'
    )
    menu = models.ForeignKey(
        'Menu',
        on_delete=models.CASCADE,
    )
    employees = models.ManyToManyField(
        'employees.Employee',
        through='EmployeeSelection'
    )

cornershop-backend-test/menus/models/slack_model.py
"""This module contains the specification the model that abstracts
the methods required to process orders

NOTICE: This model is not stored in the database
"""
from employees.models.employee import Employee


class SlackModel:
    """This class implement static methods(class methods precisely) that
    process the incoming data when an Slack action is triggered."""

    @classmethod
    def process_body(cls, body):
        """This method obtains the ids of the selected option and
        the customization added by a user in an Slack action. This
        is in order to obtain the data in the future more easily.

        :param body: The body that contains the data from the
                     triggered action in Slack
        :type body: dict

        :return: A list of strings that represent the keys
                 in the body dictionary in order to obtain
                 the required values
        :rtype:  list
        """
        state = body['state']['values']
        inputs = [slack_input['block_id'] for slack_input in body['message']['blocks']][1:]
        values = [state[oi] for oi in inputs]
        return [ops[1] for ls in values for ops in ls.items()]

    @classmethod
    def process_values(cls, values):
        """This method creates a list from the values dictionary
        in order to deliver to this class the required values
        to register or update an order.

        :param values:  List containing the data required
                        to create or update an order
                        It can have the next format
                        [
                            {
                                'type': 'radio_buttons',
                                'selected_option': {
                                    'value': The value
                                },
                            },
                            {
                                'type': 'plain_text_input',
                                'value': The value
                            }
                        ]
        :type values: list of dictionaries

        :return: Return the list of dictionaries with the
                 values required to create or update and order
        :rtype: list
        """
        output = []
        for value in values:
            if value['type'] == 'radio_buttons':
                if value['selected_option']:
                    output.append(
                        {
                            'option': value['selected_option']['value']
                        }
                    )
                if not value['selected_option']:
                    raise NotSelectedOption
            if value['type'] == 'plain_text_input':
                output.append(
                    {
                        'customization': value['value']
                    }
                )
        return output

    @classmethod
    def get_dictionary_from_values(cls, user, values):
        """This method creates the dictionary that will create or
        update an order. It also adds to it the information
        of the user.

        :param user: Dictionary containing the information of
                     a slack user
        :type user: dict
        :param values: The values of the selected option and the
                        customization of an order.
        :type values: dict

        :return: Returns the dictionary that will be used to create
                 an order or update an existing order.
        :rtype: dict
        """
        values.append({
            'slack_user_id': user['id'],
            'username': user['username']
        })
        pos = {}
        [
            pos.update(val)
            for val in values
        ]
        return pos

    @classmethod
    def create_order(cls, body):
        """This method creates or updates an order with the data
        obtained by the slack action.

        :param body: The body of the action triggered in slack
        :type body: dict
        """
        user = body['user']
        pre_processed = cls.process_body(body)
        values = cls.process_values(pre_processed)
        data = cls.get_dictionary_from_values(user, values)
        Employee.objects.create_update_order(**data)

cornershop-backend-test/menus/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Add new menú{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

cornershop-backend-test/menus/templates/create_menu.html
{% extends "base.html" %}
{% block title %} Crear menu {% endblock %}
<!--Navigation bar-->
{% block content %}
        <br/><br/>
        <!-- Content -->
        <div class="container">
            <div class="columns">
                <!--Title-->
                <div class="column">
                    <h1 class="title is-1">Crear Menú</h1>
                    <h3 class="subtitle is-3">Crea el menú para un día</h3>
                </div>
                <div class="column">
                    <button class="button" id="createMenu">Crea el Menú</button>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field">
                            <label class="label">Nombre del menú</label>
                            <div class="control">
                                <input class="input" type="text" name="name"/>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Fecha del Menú</label>
                            <div class="control">
                                <input class="datepicker input" type="text" name="date"/>
                            </div>
                        </div>
                        <h5 class="title is-5">Opciones del Menú</h5>
                        <h6 class="subtitle is-6">Crea las opciones del menú del día</h6>
                        <div class="columns">
                            <div class="column">
                                <div class="field">
                                    <label class="label">Nombre de la Opción</label>
                                    <div class="control">
                                        <input class="input" type="text" name="option-name"/>
                                    </div>
                                </div>
                            </div>
                            <div class="column">
                                <div class="field">
                                    <label class="label">Descripción de la Opción</label>
                                    <div class="control">
                                        <input class="input" type="text" name="option-name-description"/>
                                    </div>
                                </div>
                            </div>
                            <div class="column">
                                <button class="button is-primary" id="addOption">
                                    <span class="icon material-icons">
                                    add
                                    </span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="columns">
                <div id="options-cards"></div>
            </div>
        </div>
{% endblock %}
{% block scripts %}
        <script>
            var options = [];
            var datePK = $(".datepicker").datepicker();
            $("#addOption").click(function(ev){
                ev.preventDefault();
                var new_option = $("[name='option-name']").val();
                var new_description = $("[name='option-name-description']").val();
                var newObj = {
                    name: new_option,
                    description: new_description,
                };
                options.push(newObj);
                $("#options-cards").append(
                    `
                    <div class="card column" style="display: inline-block; margin:10px;">
                        <div class="card-content">
                             <div class="content">
           ${new_option} ${new_description}
                            </div>
                        </div>
                    </div>
                    `
                );
            });
            $("#createMenu").click(function(){
                var date = $(".datepicker").datepicker("getDate");
                var dateStr = date.toISOString().split('T')[0];
                var menuName = $("[name='name']").val();
                var obj = {
                    name: menuName,
                    date: dateStr,
                    options: options,
                };
                $.ajax(
                    {
                        url: "{% url 'create_menu'%}",
                        type: 'POST',
                        dataType: 'json',
                        contentType: 'application/json',
                        data: JSON.stringify(obj),
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}'                        
                        },
                        success: function(response) {
                            window.location = "{% url 'list_menus' %}";
                        },
                        error: function(response) {
                            window.location = "{% url 'list_menus' %}";
                        }
                    }
                );
            });
        </script>
{% endblock %}

cornershop-backend-test/menus/templates/list_employees_selection.html
{% extends 'base.html' %}
{% block title %} Listar Selección de Empleados {% endblock %}


{% block content %}
<br/><br/>
<div class="container">
    <div class="columns">
        {% for option in menu.menuoption_set.all %}
        <div class="column">
            <h5 class="title is-5">{{ option.name }}</h5>
            {% for employee in option.employeeselection_set.all %}
            <div class="box">
                {{ employee.employee.name  }}
                {{ employee.employee.slack_user }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}


{% block scripts %}


{% endblock %}

cornershop-backend-test/menus/templates/list_menus.html
{% extends 'base.html' %}
{% block title %} Listar menús {% endblock %}

{% block content %}
<br/><br/>

<div class="container">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h1 class="title is-1">Menú del día</h1>
                <h3 class="subtitle is-3"> Consulta el Menú del Día</h3>
            </div>
            <div class="column">
                <a class="button" href="{% url 'create_menu' %}">
                    <span class="icon material-icons">
                        add
                    </span>
                </a>
            </div>
        </div>
        <div class="columns">
            <!-- If not menu for the day -->
            {% if not menu %}
            <div class="column"></div>
            <div class="column"></div>
            <div class="column"></div>
            <div class="column">
                <div class="card has-text-centered" style="padding: 1em;">
                    <span class="icon is-large material-icons">
                        add
                    </span>
                    <br/>
                    <span>
                        Crear Menú
                    </span>
                </div>
            </div>
            <div class="column"></div>
            <div class="column"></div>
            <div class="column"></div>
            <!-- If menu for the day -->
            {% else %}
            <div class="column"></div>
            <div class="column"></div>
            <div class="column">
                <div class="card" id="menuOfTheDay">
                    <header class="card-header">
                        <p class="card-header-title">
                            {{ menu.name }}
                        </p>
                        {% if not menu.is_published %}
                        <button class="button is-success">
                            <span class="icon material-icons" id="publish">
                                publish
                            </span>
                        </button>
                        {% else %}
                        <span class="icon material-icons">
                            public
                        </span>
                        {% endif %}
                        <a class="button is-success" href="{% url 'detail_menu' menu.id %}">
                            <span class="icon material-icons">
                            visibility
                            </span>
                        </a>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <ul>
                                {% for opt in menu.menuoption_set.all %}
                                <li> {{ opt.name }} </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column"></div>
            <div class="column"></div>
            {% endif %}
        </div>
        <div class="columns">
            <div class="column">
                <h5 class="title is-5">Menús previos</h5>
                <h6 class="subtitle is-6"> Consulta los menús de otros días</h6>
            </div>
        </div>
        <div class="columns" style="margin: 10px; padding: 10px;">
            {% for menu in menus %}
            <div class="box has-text-centered" style="margin: 10px;">
                <p>{{ menu.name }}</p>
                <p>{{ menu.date }}</p>
                <br/>
                <ul>
                {% for opt in menu.menuoption_set.all %}
                <li>{{ opt.name }}</li>
                {% endfor %}
                </ul>
                <a class="button" href="{% url 'detail_menu' menu.id %}">
                    <span class="icon material-icons">visibility</span>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    "{% url 'publish_menu' menu.id as the_url %}";
    var url = '{{ the_url }}';
    if (url) {
        $('#publish').click(function(ev) {
            $.ajax({
                url: url,
                type: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                success: function(response) {
                        window.location = "{% url 'list_menus' %}";
                },
                error: function(response) {
                        window.location = "{% url 'list_menus' %}";
                }
            });
        });
    }
</script>
{% endblock %}

cornershop-backend-test/menus/templates/menu_detail.html
{% extends 'base.html'%}
{% block title %}Ver Menú{% endblock %}


{% block content%}
<br/><br/>
<div class="container">
    <div class="columns">
                
        <div class="column">
                    
            <h1 class="title is-1">Consultar Menú</h1>
                    
            <h3 class="subtitle is-3">Consulta un menú</h3>
        </div>
    </div>
    <div class="columns">
            <div class="column"></div>
            <div class="column">
                <div class="card has-text-centered">
                    <header class="card-header">
                        <p class="card-header-title">
                            {{ menu.name }}
                        </p>
                        <a class="button is-success" href="{% url 'selection' menu.id %}">
                            <span class="icon material-icons">
                                group
                            </span>
                        </a>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            Fecha del Menú: {{ menu.date }}
                        </div>
                    </div>
                    <footer class="card-footer has-text-centered" style="padding: 1em;">
                        {% if menu.is_published %}
                            El menú ya ha sido publicado
                        {% else %}
                            El menú no ha sido publicado
                            <!--Botón-->
                        {% endif %}
                    </footer>
                </div>
            </div>
            <div class="column"></div>
    </div>
    <div class="columns">
        <div class="column"></div>
        <div class="column has-text-centered">
            <h5 class="title is-5">Opciones del Menú</h5>
        </div>
        <div class="column"></div>
    </div>
    <div class="columns">
        <div>
            {% for opt in menu.menuoption_set.all %}
            <div class="card column" style="display: inline-block; margin: 10px;">
                <div class="card-content">
                    <div class="content">
                        {{ opt.name }} {{ opt.description }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div> 
    </div>

</div>

{% endblock %}

cornershop-backend-test/menus/templates/navbar.html
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="https://bulma.io">
                    <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
                </a>
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if not user.is_authenticated %}
                        <a class="button is-light">
                            Log in
                        </a>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <p>
                        {{ user.username }}
                        </p>
                        <a class="button is-light" href="{% url 'logout' %}">
                            Log Out
                        </a>
                        {% endif %}
                    </div>
                 </div>
            </div>
        </nav>